const ninos = [
  { id: 1, codigo: "alan", caption: "Alan", fotos: ["alan.JPG"] },
  { id: 2, codigo: "ariadna", caption: "Ariadna", fotos: ["ariatna.JPG"] },
  { id: 3, codigo: "bruno", caption: "Bruno", fotos: ["bruno.JPG"] },
  { id: 4, codigo: "carlos", caption: "Carlos", fotos: ["carlos.JPG"] },
  { id: 5, codigo: "celia", caption: "Celia", fotos: ["celia.JPG"] },
  { id: 6, codigo: "elizabeth", caption: "Elizabeth", fotos: ["elizabeth.JPG"] },
  { id: 7, codigo: "emily", caption: "Emily", fotos: [] },
  { id: 8, codigo: "hectorgael", caption: "Hector Gael", fotos: ["hector.JPG"] },
  { id: 9, codigo: "itzayana", caption: "Itzayana", fotos: ["itzayana.JPG"] },
  { id: 10, codigo: "leah", caption: "Leah", fotos: ["lea.JPG"] },
  { id: 11, codigo: "mia", caption: "Mia", fotos: ["mia.JPG"] },
  { id: 12, codigo: "montserrath", caption: "Montserrath", fotos: ["monserrat.JPG"] },
  { id: 13, codigo: "nahomi", caption: "Nahomi", fotos: ["nahomi aguilar.JPG"] },
  { id: 14, codigo: "nahum", caption: "Nahum", fotos: ["nahum.JPG"] },
  { id: 15, codigo: "naomi", caption: "Naomi", fotos: ["naomi.JPG"] },
  { id: 16, codigo: "ximena", caption: "Ximena", fotos: ["ximena.JPG"] },
  { id: 17, codigo: "yoarp", caption: "Yoarp", fotos: ["yoarp.JPG"] },
];

const portadas = [
  "alan-paquete2.jpg",
  "ariadna-paquete1.jpg",
  "bruno-paquete1.jpg",
  "carlos-paquete1.jpg",
  "celia-paquete1.jpg",
  "elizabeth-paquete1.jpg",
  "emily-paquete1.jpg",
  "hectorgael-paquete1.jpg",
  "itzayana-paquete2.jpg",
  "leah-paquete2.jpg",
  "mia-paquete2.jpg",
  "montserrath-paquete1.jpg",
  "nahomi-paquete2.jpg",
  "nahum-paquete1.jpg",
  "naomi-paquete1.jpg",
  "ximena-paquete1.jpg",
  "yoarp-paquete1.jpg",
];