const ninos = [
  { id: 1, codigo: "se01", caption: "Aldo", fotos: ["1/aldo.JPG", "1/familia.jpg"] },
  { id: 2, codigo: "se02", caption: "Angel", fotos: ["2/angel blanco.JPG", "2/familia.jpg"] },
  { id: 3, codigo: "se03", caption: "Arisbeth", fotos: [] },
  { id: 4, codigo: "se04", caption: "Axel", fotos: ["4/axel.jpg"] },
  { id: 5, codigo: "se05", caption: "Camila", fotos: ["5/camila.JPG", "5/familia.jpg"] },
  { id: 6, codigo: "se06", caption: "Cesar", fotos: ["6/cesar.JPG", "6/familia.jpg"] },
  { id: 7, codigo: "se07", caption: "Delmar", fotos: ["7/delmar.JPG", "7/familia.jpg"] },
  { id: 8, codigo: "se08", caption: "Diana", fotos: ["8/diana.JPG", "8/familia.jpg"] },
  { id: 9, codigo: "se09", caption: "Jorge", fotos: ["9/jorge.JPG", "9/familia.jpg"] },
  { id: 10, codigo: "se10", caption: "Karen", fotos: ["10/karen.JPG", "10/familia.jpg"] },
  { id: 11, codigo: "se11", caption: "Karla Aracely", fotos: ["11/aracely.JPG", "11/familia.jpg"] },
  { id: 12, codigo: "se12", caption: "Karla Valeria", fotos: ["12/karla valeria .JPG", "12/familia.jpg"] },
  { id: 13, codigo: "se13", caption: "Luis Adrian", fotos: ["13/familia.jpg"] },
  { id: 14, codigo: "se14", caption: "Luis Artemio", fotos: ["14/luis artemio.JPG", "14/familia.jpg"] },
  { id: 15, codigo: "se15", caption: "Luis Gustavo", fotos: ["15/familia.jpg"] },
  { id: 16, codigo: "se16", caption: "Maite", fotos: ["16/maite.JPG", "16/familia.jpg"] },
  { id: 17, codigo: "se17", caption: "Maria Jose", fotos: [] },
  { id: 18, codigo: "se18", caption: "Nahomi", fotos: ["18/nahomi trujillo.JPG", "18/familia.jpg"] },
  { id: 19, codigo: "se19", caption: "Valeria", fotos: ["19/valeria.JPG", "19/familia.jpg"] },
  { id: 20, codigo: "se20", caption: "Veronica", fotos: ["20/veronica.JPG", "20/familia.jpg"] },
  { id: 21, codigo: "se21", caption: "Ximena", fotos: ["21/ximena.JPG", "21/familia.jpg"] },
  { id: 22, codigo: "se22", caption: "Ximena Solail", fotos: ["22/ximena solai.JPG", "22/familia.jpg"] },
  { id: 23, codigo: "se23", caption: "Yatziri", fotos: ["23/yatziri.JPG", "23/familia.jpg"] },
  { id: 24, codigo: "se24", caption: "Uriel", fotos: ["24/uriel.jpg", "24/familia.jpg"] },
  { id: 25, codigo: "se25", caption: "Abdel", fotos: ["25/abdel.jpg", "25/familia.jpg"] },
];

const portadas = [
  "aldo-paquete1.jpg",
  "angel-paquete2.jpg",
  "arisbeth-paquete1.jpg",
  "axel-paquete2.jpg",
  "camila-paquete2.jpg",
  "cesar-paquete2.jpg",
  "delmar-paquete2.jpg",
  "diana-paquete1.jpg",
  "jorge-paquete1.jpg",
  "karen-paquete2.jpg",
  "karlaaracely-paquete1.jpg",
  "karlavaleria-paquete1.jpg",
  "luisadrian-paquete2.jpg",
  "luisartemio-paquete1.jpg",
  "luisgustavo-paquete2.jpg",
  "maite-paquete2.jpg",
  "mariajose-paquete2.jpg",
  "nahomi-paquete2.jpg",
  "valeria-paquete2.jpg",
  "veronica-paquete1.jpg",
  "ximena-paquete1.jpg",
  "ximenasolail-paquete2.jpg",
  "yatziri-paquete1.jpg",
  "uriel-portada.jpg",
  "abdel-portada.jpg",
];