const ninos = [
  { id: 1, codigo: "se01", caption: "Aldo", fotos: ["aldo.JPG"] },
  { id: 2, codigo: "se02", caption: "Angel", fotos: ["angel blanco.JPG"] },
  { id: 3, codigo: "se03", caption: "Arisbeth", fotos: [] },
  { id: 4, codigo: "se04", caption: "Axel", fotos: [] },
  { id: 5, codigo: "se05", caption: "Camila", fotos: ["camila.JPG"] },
  { id: 6, codigo: "se06", caption: "Cesar", fotos: ["cesar.JPG"] },
  { id: 7, codigo: "se07", caption: "Delmar", fotos: ["delmar.JPG"] },
  { id: 8, codigo: "se08", caption: "Diana", fotos: ["diana.JPG"] },
  { id: 9, codigo: "se09", caption: "Jorge", fotos: ["jorge.JPG"] },
  { id: 10, codigo: "se10", caption: "Karen", fotos: ["karen.JPG"] },
  { id: 11, codigo: "se11", caption: "Karla Aracely", fotos: ["aracely.JPG"] },
  { id: 12, codigo: "se12", caption: "Karla Valeria", fotos: ["karla valeria .JPG"] },
  { id: 13, codigo: "se13", caption: "Luis Adrian", fotos: [] },
  { id: 14, codigo: "se14", caption: "Luis Artemio", fotos: ["luis artemio.JPG"] },
  { id: 15, codigo: "se15", caption: "Luis Gustavo", fotos: [] },
  { id: 16, codigo: "se16", caption: "Maite", fotos: ["maite.JPG"] },
  { id: 17, codigo: "se17", caption: "Maria Jose", fotos: [] },
  { id: 18, codigo: "se18", caption: "Nahomi", fotos: ["nahomi trujillo.JPG"] },
  { id: 19, codigo: "se19", caption: "Valeria", fotos: ["valeria.JPG"] },
  { id: 20, codigo: "se20", caption: "Veronica", fotos: ["veronica.JPG"] },
  { id: 21, codigo: "se21", caption: "Ximena", fotos: ["ximena.JPG"] },
  { id: 22, codigo: "se22", caption: "Ximena Solail", fotos: ["ximena solai.JPG"] },
  { id: 23, codigo: "se23", caption: "Yatziri", fotos: ["yatziri.JPG"] },
];

const portadas = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];